[package]
name = "tinki"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

[dependencies]
spongedown = "0.3.1"
stdweb = "0.4"
web_logger = "0.1"
log = "0.4"
yew = {path = "../yew"}

[replace]
"spongedown:0.3.1" = { path = "../spongedown" } 
